main: relampagorojo93.ViceProperties.PropertiesMain
name: Propiedades
author: relampagorojo93
version: 1.0
api-version: 1.13
description: ViceProperties
depend: [WorldGuard, WorldEdit, TokenManager]

commands:
    vprop:
        description: Get All Commands
