main: us.mytheria.privateproperties.PropertiesMain
name: PrivateProperties
author: ProMoRRom
version: 1.0
api-version: 1.16
description: ViceProperties
depend: [WorldGuard, WorldEdit, TokenManager]

commands:
    vprop:
        description: Get All Commands